models:
  image: tp33/django
  container_name: models
  external_links:
    - mysql:db
  volumes:
    - "$PWD/app/models:/app"
  ports:
    - "8001:8000"
  command: bash -c "mod_wsgi-express start-server  --working-directory . --reload-on-changes models/wsgi.py"

exp:
  image: tp33/django
  container_name: exp
  links:
    - models:models-api
  volumes:
    - "$PWD/app/exp:/app"
  ports:
    - "8002:8000"
  command: bash -c "mod_wsgi-express start-server  --working-directory . --reload-on-changes exp/wsgi.py"


web:
  image: tp33/django
  container_name: web
  links:
    - exp:exp-api
  volumes:
    - "$PWD/app/web:/app"
  ports:
    - "8000:8000"
  command: bash -c "mod_wsgi-express start-server --working-directory . --reload-on-changes web/wsgi.py"
