# Generated by Django 2.1 on 2018-10-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
